const PERSON_LIST = 'PERSON_LIST';
const PERSON_CREATE = 'PERSON_CREATE'
const PERSON_ONE = "PERSON_ONE"
const PERSON_DELETE = "PERSON_DELETE"
const PERSON_EDIT = "PERSON_EDIT"

const types = {
    PERSON_LIST,
    PERSON_CREATE,
    PERSON_ONE,
    PERSON_DELETE,
    PERSON_EDIT
};

export default types;