version: "3"
services:
  app:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - /usr/src/app/node_modules
      - ./react/src:/usr/src/app/src/
      - ./react/public:/usr/src/app/public/

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      PGHOST: "postgres"
      PGPORT: "5432"
      PGDATABASE: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
    volumes:
      - /usr/src/app/node_modules
      - ./backend/src:/usr/src/app/src
  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - /var/lib/postgresql

