version: '3'

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  api:
    build:
      context: redis
      dockerfile: ./Dockerfile
    links:
      - redis
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./redis:/home/node/app
    


